# Use :nonroot base image for all containers
# defaultBaseImage: gcr.io/distroless/static:nonroot
# Use: busybox to debug container
# baseImageOverrides:
#   github.com/seidu626/audiobook/account-service: busybox
#   github.com/seidu626/audiobook/emailer-service: busybox

# defaultBaseImage: gcr.io/distroless/base
