// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/language/proto/entities/entities.proto

package entities

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Exercise struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Content              string               `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	AudioSrc             string               `protobuf:"bytes,6,opt,name=audio_src,json=audioSrc,proto3" json:"audio_src,omitempty"`
	Skill                *Skill               `protobuf:"bytes,7,opt,name=Skill,proto3" json:"Skill,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Exercise) Reset()         { *m = Exercise{} }
func (m *Exercise) String() string { return proto.CompactTextString(m) }
func (*Exercise) ProtoMessage()    {}
func (*Exercise) Descriptor() ([]byte, []int) {
	return fileDescriptor_db3e511474781d95, []int{0}
}

func (m *Exercise) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Exercise.Unmarshal(m, b)
}
func (m *Exercise) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Exercise.Marshal(b, m, deterministic)
}
func (m *Exercise) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Exercise.Merge(m, src)
}
func (m *Exercise) XXX_Size() int {
	return xxx_messageInfo_Exercise.Size(m)
}
func (m *Exercise) XXX_DiscardUnknown() {
	xxx_messageInfo_Exercise.DiscardUnknown(m)
}

var xxx_messageInfo_Exercise proto.InternalMessageInfo

func (m *Exercise) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Exercise) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Exercise) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Exercise) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *Exercise) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Exercise) GetAudioSrc() string {
	if m != nil {
		return m.AudioSrc
	}
	return ""
}

func (m *Exercise) GetSkill() *Skill {
	if m != nil {
		return m.Skill
	}
	return nil
}

//
// A skill is a set of lessons focused on a particular topic, such as present
// tense verbs or sports vocabulary. https://duolingo.fandom.com/wiki/Skill
type Skill struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp  `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp  `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp  `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Dependencies         *wrappers.StringValue `protobuf:"bytes,5,opt,name=dependencies,proto3" json:"dependencies,omitempty"`
	LessonNumber         int32                 `protobuf:"varint,7,opt,name=lesson_number,json=lessonNumber,proto3" json:"lesson_number,omitempty"`
	Description          *wrappers.StringValue `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Locked               bool                  `protobuf:"varint,9,opt,name=locked,proto3" json:"locked,omitempty"`
	Type                 *wrappers.StringValue `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`
	Title                string                `protobuf:"bytes,11,opt,name=title,proto3" json:"title,omitempty"`
	UrlTitle             string                `protobuf:"bytes,12,opt,name=url_title,json=urlTitle,proto3" json:"url_title,omitempty"`
	Category             *wrappers.StringValue `protobuf:"bytes,13,opt,name=category,proto3" json:"category,omitempty"`
	Index                int32                 `protobuf:"varint,14,opt,name=index,proto3" json:"index,omitempty"`
	Words                []*Word               `protobuf:"bytes,15,rep,name=words,proto3" json:"words,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Skill) Reset()         { *m = Skill{} }
func (m *Skill) String() string { return proto.CompactTextString(m) }
func (*Skill) ProtoMessage()    {}
func (*Skill) Descriptor() ([]byte, []int) {
	return fileDescriptor_db3e511474781d95, []int{1}
}

func (m *Skill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Skill.Unmarshal(m, b)
}
func (m *Skill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Skill.Marshal(b, m, deterministic)
}
func (m *Skill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Skill.Merge(m, src)
}
func (m *Skill) XXX_Size() int {
	return xxx_messageInfo_Skill.Size(m)
}
func (m *Skill) XXX_DiscardUnknown() {
	xxx_messageInfo_Skill.DiscardUnknown(m)
}

var xxx_messageInfo_Skill proto.InternalMessageInfo

func (m *Skill) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Skill) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Skill) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Skill) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *Skill) GetDependencies() *wrappers.StringValue {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

func (m *Skill) GetLessonNumber() int32 {
	if m != nil {
		return m.LessonNumber
	}
	return 0
}

func (m *Skill) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *Skill) GetLocked() bool {
	if m != nil {
		return m.Locked
	}
	return false
}

func (m *Skill) GetType() *wrappers.StringValue {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Skill) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Skill) GetUrlTitle() string {
	if m != nil {
		return m.UrlTitle
	}
	return ""
}

func (m *Skill) GetCategory() *wrappers.StringValue {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *Skill) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Skill) GetWords() []*Word {
	if m != nil {
		return m.Words
	}
	return nil
}

type Word struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Content              string               `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	AudioSrc             string               `protobuf:"bytes,6,opt,name=audio_src,json=audioSrc,proto3" json:"audio_src,omitempty"`
	Skill_Id             string               `protobuf:"bytes,7,opt,name=skill_Id,json=skillId,proto3" json:"skill_Id,omitempty"`
	Skill                *Skill               `protobuf:"bytes,8,opt,name=Skill,proto3" json:"Skill,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Word) Reset()         { *m = Word{} }
func (m *Word) String() string { return proto.CompactTextString(m) }
func (*Word) ProtoMessage()    {}
func (*Word) Descriptor() ([]byte, []int) {
	return fileDescriptor_db3e511474781d95, []int{2}
}

func (m *Word) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Word.Unmarshal(m, b)
}
func (m *Word) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Word.Marshal(b, m, deterministic)
}
func (m *Word) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Word.Merge(m, src)
}
func (m *Word) XXX_Size() int {
	return xxx_messageInfo_Word.Size(m)
}
func (m *Word) XXX_DiscardUnknown() {
	xxx_messageInfo_Word.DiscardUnknown(m)
}

var xxx_messageInfo_Word proto.InternalMessageInfo

func (m *Word) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Word) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Word) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Word) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *Word) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Word) GetAudioSrc() string {
	if m != nil {
		return m.AudioSrc
	}
	return ""
}

func (m *Word) GetSkill_Id() string {
	if m != nil {
		return m.Skill_Id
	}
	return ""
}

func (m *Word) GetSkill() *Skill {
	if m != nil {
		return m.Skill
	}
	return nil
}

// Language Entity
type Language struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Name                 string               `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Abbreviation         string               `protobuf:"bytes,6,opt,name=abbreviation,proto3" json:"abbreviation,omitempty"`
	FlagSrc              string               `protobuf:"bytes,7,opt,name=flag_src,json=flagSrc,proto3" json:"flag_src,omitempty"`
	Skills               []*Skill             `protobuf:"bytes,9,rep,name=skills,proto3" json:"skills,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Language) Reset()         { *m = Language{} }
func (m *Language) String() string { return proto.CompactTextString(m) }
func (*Language) ProtoMessage()    {}
func (*Language) Descriptor() ([]byte, []int) {
	return fileDescriptor_db3e511474781d95, []int{3}
}

func (m *Language) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Language.Unmarshal(m, b)
}
func (m *Language) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Language.Marshal(b, m, deterministic)
}
func (m *Language) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Language.Merge(m, src)
}
func (m *Language) XXX_Size() int {
	return xxx_messageInfo_Language.Size(m)
}
func (m *Language) XXX_DiscardUnknown() {
	xxx_messageInfo_Language.DiscardUnknown(m)
}

var xxx_messageInfo_Language proto.InternalMessageInfo

func (m *Language) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Language) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Language) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Language) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *Language) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Language) GetAbbreviation() string {
	if m != nil {
		return m.Abbreviation
	}
	return ""
}

func (m *Language) GetFlagSrc() string {
	if m != nil {
		return m.FlagSrc
	}
	return ""
}

func (m *Language) GetSkills() []*Skill {
	if m != nil {
		return m.Skills
	}
	return nil
}

func init() {
	proto.RegisterType((*Exercise)(nil), "audiobook.language.entities.v1.Exercise")
	proto.RegisterType((*Skill)(nil), "audiobook.language.entities.v1.Skill")
	proto.RegisterType((*Word)(nil), "audiobook.language.entities.v1.Word")
	proto.RegisterType((*Language)(nil), "audiobook.language.entities.v1.Language")
}

func init() {
	proto.RegisterFile("services/language/proto/entities/entities.proto", fileDescriptor_db3e511474781d95)
}

var fileDescriptor_db3e511474781d95 = []byte{
	// 577 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x95, 0xdf, 0x6a, 0x13, 0x41,
	0x14, 0xc6, 0x49, 0x9a, 0xa4, 0xbb, 0x93, 0xb4, 0xc2, 0x20, 0x32, 0x56, 0xa9, 0x21, 0x2a, 0xe4,
	0x6a, 0x57, 0x23, 0x14, 0xff, 0xa0, 0x58, 0x41, 0xb1, 0x20, 0x5e, 0x6c, 0x8b, 0x82, 0x37, 0x61,
	0x76, 0xe6, 0x74, 0x1d, 0x32, 0x99, 0x59, 0x66, 0x66, 0xd3, 0xf6, 0xe9, 0x7c, 0x0b, 0xef, 0x7c,
	0x0f, 0x2f, 0x65, 0x67, 0x27, 0xd1, 0x2a, 0x98, 0xe0, 0x5d, 0xf1, 0x6e, 0xbf, 0x33, 0xdf, 0x77,
	0x0e, 0xfd, 0xf5, 0x1c, 0x82, 0x52, 0x0b, 0x66, 0x21, 0x18, 0xd8, 0x54, 0x52, 0x55, 0x54, 0xb4,
	0x80, 0xb4, 0x34, 0xda, 0xe9, 0x14, 0x94, 0x13, 0x4e, 0x80, 0x5d, 0x7d, 0x24, 0xbe, 0x8e, 0xf7,
	0x69, 0xc5, 0x85, 0xce, 0xb5, 0x9e, 0x25, 0xcb, 0x44, 0xb2, 0xb2, 0x2c, 0x1e, 0xee, 0xdd, 0x29,
	0xb4, 0x2e, 0x64, 0xe8, 0x92, 0x57, 0xa7, 0xa9, 0x13, 0x73, 0xb0, 0x8e, 0xce, 0xcb, 0xa6, 0xc1,
	0xde, 0xfe, 0xef, 0x86, 0x33, 0x43, 0xcb, 0x12, 0x4c, 0x18, 0x30, 0xfa, 0xd2, 0x46, 0xd1, 0xeb,
	0x73, 0x30, 0x4c, 0x58, 0xc0, 0xbb, 0xa8, 0x2d, 0x38, 0x69, 0x0d, 0x5b, 0xe3, 0x38, 0x6b, 0x0b,
	0x8e, 0x9f, 0x20, 0xc4, 0x0c, 0x50, 0x07, 0x7c, 0x4a, 0x1d, 0x69, 0x0f, 0x5b, 0xe3, 0xfe, 0x64,
	0x2f, 0x69, 0x3a, 0x26, 0xcb, 0x8e, 0xc9, 0xc9, 0x72, 0x64, 0x16, 0x07, 0xf7, 0xa1, 0xab, 0xa3,
	0x55, 0xc9, 0x97, 0xd1, 0xad, 0xf5, 0xd1, 0xe0, 0x6e, 0xa2, 0x1c, 0x24, 0x84, 0x68, 0x67, 0x7d,
	0x34, 0xb8, 0x0f, 0x1d, 0x26, 0x68, 0x9b, 0x69, 0xe5, 0x40, 0x39, 0xd2, 0xf5, 0x7f, 0xc5, 0x52,
	0xe2, 0x5b, 0x28, 0xf6, 0x28, 0xa7, 0xd6, 0x30, 0xd2, 0xf3, 0x6f, 0x91, 0x2f, 0x1c, 0x1b, 0x86,
	0x9f, 0xa1, 0xee, 0xf1, 0x4c, 0x48, 0x49, 0xb6, 0xfd, 0xb0, 0xfb, 0xc9, 0xdf, 0xa9, 0x27, 0xde,
	0x9c, 0x35, 0x99, 0xd1, 0xf7, 0x4e, 0x48, 0x5f, 0x7d, 0x7c, 0x2f, 0xd1, 0x80, 0x43, 0x09, 0x8a,
	0x83, 0x62, 0x02, 0xac, 0x67, 0xd8, 0x9f, 0xdc, 0xfe, 0x23, 0x7c, 0xec, 0x8c, 0x50, 0xc5, 0x07,
	0x2a, 0x2b, 0xc8, 0x2e, 0x25, 0xf0, 0x5d, 0xb4, 0x23, 0xc1, 0x5a, 0xad, 0xa6, 0xaa, 0x9a, 0xe7,
	0x60, 0x3c, 0xd1, 0x6e, 0x36, 0x68, 0x8a, 0xef, 0x7d, 0x0d, 0xbf, 0x40, 0x7d, 0x0e, 0x96, 0x19,
	0x51, 0x3a, 0xa1, 0x15, 0x89, 0x36, 0x98, 0xf2, 0x6b, 0x00, 0xdf, 0x40, 0x3d, 0xa9, 0xd9, 0x0c,
	0x38, 0x89, 0x87, 0xad, 0x71, 0x94, 0x05, 0x85, 0x1f, 0xa0, 0x8e, 0xbb, 0x28, 0x81, 0xa0, 0x0d,
	0x1a, 0x7a, 0x27, 0xbe, 0x8e, 0xba, 0x4e, 0x38, 0x09, 0xa4, 0xef, 0xff, 0x69, 0x8d, 0xa8, 0x77,
	0xa5, 0x32, 0x72, 0xda, 0xbc, 0x0c, 0x9a, 0x5d, 0xa9, 0x8c, 0x3c, 0xf1, 0x8f, 0x8f, 0x51, 0xc4,
	0xa8, 0x83, 0x42, 0x9b, 0x0b, 0xb2, 0xb3, 0xc1, 0xa0, 0x95, 0xbb, 0x1e, 0x26, 0x14, 0x87, 0x73,
	0xb2, 0xeb, 0x99, 0x34, 0x02, 0x3f, 0x45, 0xdd, 0x33, 0x6d, 0xb8, 0x25, 0xd7, 0x86, 0x5b, 0xe3,
	0xfe, 0xe4, 0xde, 0xba, 0xdd, 0xfb, 0xa8, 0x0d, 0xcf, 0x9a, 0xc8, 0xe8, 0x6b, 0x1b, 0x75, 0x6a,
	0xfd, 0xdf, 0x1e, 0xee, 0x4d, 0x14, 0xd9, 0xfa, 0xf4, 0xa6, 0x47, 0xdc, 0x6f, 0x5a, 0x9c, 0x6d,
	0x7b, 0x7d, 0xc4, 0x7f, 0xde, 0x74, 0xf4, 0x0f, 0x37, 0xfd, 0xad, 0x8d, 0xa2, 0x77, 0xc1, 0x75,
	0xf5, 0xe1, 0x62, 0xd4, 0x51, 0x74, 0x0e, 0x81, 0xac, 0xff, 0xc6, 0x23, 0x34, 0xa0, 0x79, 0x6e,
	0x60, 0x21, 0xa8, 0x3f, 0xc2, 0x86, 0xec, 0xa5, 0x5a, 0x4d, 0xf7, 0x54, 0xd2, 0xc2, 0x93, 0x0f,
	0x74, 0x6b, 0x5d, 0x83, 0x7f, 0x8e, 0x7a, 0x1e, 0xb4, 0x25, 0xb1, 0x5f, 0xdb, 0x0d, 0xf1, 0x86,
	0xd0, 0xab, 0xb7, 0x9f, 0xde, 0x14, 0xc2, 0x7d, 0xae, 0xf2, 0x84, 0xe9, 0x79, 0x6a, 0x41, 0xf0,
	0xea, 0x60, 0x72, 0x90, 0xae, 0x7a, 0xa4, 0x39, 0x65, 0x33, 0x50, 0x7c, 0xed, 0xef, 0x65, 0xde,
	0xf3, 0xfa, 0xd1, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc0, 0xe0, 0xce, 0xe5, 0x5a, 0x07, 0x00,
	0x00,
}
