// source: service/language/proto/entities/entities.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var third_party_proto_protoc$gen$gorm_options_gorm_pb = require('../../../../backend/third_party/proto/protoc-gen-gorm/options/gorm_pb.js');
goog.object.extend(proto, third_party_proto_protoc$gen$gorm_options_gorm_pb);
var third_party_proto_protoc$gen$gorm_types_types_pb = require('../../../../backend/third_party/proto/protoc-gen-gorm/types/types_pb.js');
goog.object.extend(proto, third_party_proto_protoc$gen$gorm_types_types_pb);
var third_party_proto_validate_validate_pb = require('../../../../backend/third_party/proto/validate/validate_pb.js');
goog.object.extend(proto, third_party_proto_validate_validate_pb);
goog.exportSymbol('proto.micro.service.language.entities.v1.Exercise', null, global);
goog.exportSymbol('proto.micro.service.language.entities.v1.Language', null, global);
goog.exportSymbol('proto.micro.service.language.entities.v1.Skill', null, global);
goog.exportSymbol('proto.micro.service.language.entities.v1.Word', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.micro.service.language.entities.v1.Exercise = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.micro.service.language.entities.v1.Exercise, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.micro.service.language.entities.v1.Exercise.displayName = 'proto.micro.service.language.entities.v1.Exercise';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.micro.service.language.entities.v1.Skill = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.micro.service.language.entities.v1.Skill.repeatedFields_, null);
};
goog.inherits(proto.micro.service.language.entities.v1.Skill, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.micro.service.language.entities.v1.Skill.displayName = 'proto.micro.service.language.entities.v1.Skill';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.micro.service.language.entities.v1.Word = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.micro.service.language.entities.v1.Word, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.micro.service.language.entities.v1.Word.displayName = 'proto.micro.service.language.entities.v1.Word';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.micro.service.language.entities.v1.Language = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.micro.service.language.entities.v1.Language.repeatedFields_, null);
};
goog.inherits(proto.micro.service.language.entities.v1.Language, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.micro.service.language.entities.v1.Language.displayName = 'proto.micro.service.language.entities.v1.Language';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.micro.service.language.entities.v1.Exercise.prototype.toObject = function(opt_includeInstance) {
  return proto.micro.service.language.entities.v1.Exercise.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.micro.service.language.entities.v1.Exercise} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.micro.service.language.entities.v1.Exercise.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = msg.getId()) && third_party_proto_protoc$gen$gorm_types_types_pb.UUID.toObject(includeInstance, f),
    createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    deletedAt: (f = msg.getDeletedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    content: jspb.Message.getFieldWithDefault(msg, 5, ""),
    audioSrc: jspb.Message.getFieldWithDefault(msg, 6, ""),
    skill: (f = msg.getSkill()) && proto.micro.service.language.entities.v1.Skill.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.micro.service.language.entities.v1.Exercise}
 */
proto.micro.service.language.entities.v1.Exercise.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.micro.service.language.entities.v1.Exercise;
  return proto.micro.service.language.entities.v1.Exercise.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.micro.service.language.entities.v1.Exercise} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.micro.service.language.entities.v1.Exercise}
 */
proto.micro.service.language.entities.v1.Exercise.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new third_party_proto_protoc$gen$gorm_types_types_pb.UUID;
      reader.readMessage(value,third_party_proto_protoc$gen$gorm_types_types_pb.UUID.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDeletedAt(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setContent(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setAudioSrc(value);
      break;
    case 7:
      var value = new proto.micro.service.language.entities.v1.Skill;
      reader.readMessage(value,proto.micro.service.language.entities.v1.Skill.deserializeBinaryFromReader);
      msg.setSkill(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.micro.service.language.entities.v1.Exercise.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.micro.service.language.entities.v1.Exercise.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.micro.service.language.entities.v1.Exercise} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.micro.service.language.entities.v1.Exercise.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      third_party_proto_protoc$gen$gorm_types_types_pb.UUID.serializeBinaryToWriter
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDeletedAt();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getContent();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getAudioSrc();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getSkill();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.micro.service.language.entities.v1.Skill.serializeBinaryToWriter
    );
  }
};


/**
 * optional gorm.types.UUID id = 1;
 * @return {?proto.gorm.types.UUID}
 */
proto.micro.service.language.entities.v1.Exercise.prototype.getId = function() {
  return /** @type{?proto.gorm.types.UUID} */ (
    jspb.Message.getWrapperField(this, third_party_proto_protoc$gen$gorm_types_types_pb.UUID, 1));
};


/**
 * @param {?proto.gorm.types.UUID|undefined} value
 * @return {!proto.micro.service.language.entities.v1.Exercise} returns this
*/
proto.micro.service.language.entities.v1.Exercise.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.micro.service.language.entities.v1.Exercise} returns this
 */
proto.micro.service.language.entities.v1.Exercise.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.micro.service.language.entities.v1.Exercise.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.Timestamp created_at = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.micro.service.language.entities.v1.Exercise.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.micro.service.language.entities.v1.Exercise} returns this
*/
proto.micro.service.language.entities.v1.Exercise.prototype.setCreatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.micro.service.language.entities.v1.Exercise} returns this
 */
proto.micro.service.language.entities.v1.Exercise.prototype.clearCreatedAt = function() {
  return this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.micro.service.language.entities.v1.Exercise.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.micro.service.language.entities.v1.Exercise.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.micro.service.language.entities.v1.Exercise} returns this
*/
proto.micro.service.language.entities.v1.Exercise.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.micro.service.language.entities.v1.Exercise} returns this
 */
proto.micro.service.language.entities.v1.Exercise.prototype.clearUpdatedAt = function() {
  return this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.micro.service.language.entities.v1.Exercise.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.Timestamp deleted_at = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.micro.service.language.entities.v1.Exercise.prototype.getDeletedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.micro.service.language.entities.v1.Exercise} returns this
*/
proto.micro.service.language.entities.v1.Exercise.prototype.setDeletedAt = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.micro.service.language.entities.v1.Exercise} returns this
 */
proto.micro.service.language.entities.v1.Exercise.prototype.clearDeletedAt = function() {
  return this.setDeletedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.micro.service.language.entities.v1.Exercise.prototype.hasDeletedAt = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string content = 5;
 * @return {string}
 */
proto.micro.service.language.entities.v1.Exercise.prototype.getContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.micro.service.language.entities.v1.Exercise} returns this
 */
proto.micro.service.language.entities.v1.Exercise.prototype.setContent = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string audio_src = 6;
 * @return {string}
 */
proto.micro.service.language.entities.v1.Exercise.prototype.getAudioSrc = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.micro.service.language.entities.v1.Exercise} returns this
 */
proto.micro.service.language.entities.v1.Exercise.prototype.setAudioSrc = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional Skill Skill = 7;
 * @return {?proto.micro.service.language.entities.v1.Skill}
 */
proto.micro.service.language.entities.v1.Exercise.prototype.getSkill = function() {
  return /** @type{?proto.micro.service.language.entities.v1.Skill} */ (
    jspb.Message.getWrapperField(this, proto.micro.service.language.entities.v1.Skill, 7));
};


/**
 * @param {?proto.micro.service.language.entities.v1.Skill|undefined} value
 * @return {!proto.micro.service.language.entities.v1.Exercise} returns this
*/
proto.micro.service.language.entities.v1.Exercise.prototype.setSkill = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.micro.service.language.entities.v1.Exercise} returns this
 */
proto.micro.service.language.entities.v1.Exercise.prototype.clearSkill = function() {
  return this.setSkill(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.micro.service.language.entities.v1.Exercise.prototype.hasSkill = function() {
  return jspb.Message.getField(this, 7) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.micro.service.language.entities.v1.Skill.repeatedFields_ = [15];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.micro.service.language.entities.v1.Skill.prototype.toObject = function(opt_includeInstance) {
  return proto.micro.service.language.entities.v1.Skill.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.micro.service.language.entities.v1.Skill} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.micro.service.language.entities.v1.Skill.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = msg.getId()) && third_party_proto_protoc$gen$gorm_types_types_pb.UUID.toObject(includeInstance, f),
    createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    deletedAt: (f = msg.getDeletedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    dependencies: (f = msg.getDependencies()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    disabled: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    lessonNumber: jspb.Message.getFieldWithDefault(msg, 7, 0),
    description: (f = msg.getDescription()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    locked: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
    type: (f = msg.getType()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    title: jspb.Message.getFieldWithDefault(msg, 11, ""),
    urlTitle: jspb.Message.getFieldWithDefault(msg, 12, ""),
    category: (f = msg.getCategory()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    index: jspb.Message.getFieldWithDefault(msg, 14, 0),
    wordsList: jspb.Message.toObjectList(msg.getWordsList(),
    proto.micro.service.language.entities.v1.Word.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.micro.service.language.entities.v1.Skill}
 */
proto.micro.service.language.entities.v1.Skill.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.micro.service.language.entities.v1.Skill;
  return proto.micro.service.language.entities.v1.Skill.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.micro.service.language.entities.v1.Skill} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.micro.service.language.entities.v1.Skill}
 */
proto.micro.service.language.entities.v1.Skill.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new third_party_proto_protoc$gen$gorm_types_types_pb.UUID;
      reader.readMessage(value,third_party_proto_protoc$gen$gorm_types_types_pb.UUID.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDeletedAt(value);
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setDependencies(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDisabled(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLessonNumber(value);
      break;
    case 8:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setDescription(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setLocked(value);
      break;
    case 10:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setType(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrlTitle(value);
      break;
    case 13:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setCategory(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIndex(value);
      break;
    case 15:
      var value = new proto.micro.service.language.entities.v1.Word;
      reader.readMessage(value,proto.micro.service.language.entities.v1.Word.deserializeBinaryFromReader);
      msg.addWords(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.micro.service.language.entities.v1.Skill.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.micro.service.language.entities.v1.Skill.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.micro.service.language.entities.v1.Skill} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.micro.service.language.entities.v1.Skill.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      third_party_proto_protoc$gen$gorm_types_types_pb.UUID.serializeBinaryToWriter
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDeletedAt();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDependencies();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getDisabled();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getLessonNumber();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getDescription();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getLocked();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getType();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getUrlTitle();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getCategory();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getIndex();
  if (f !== 0) {
    writer.writeInt32(
      14,
      f
    );
  }
  f = message.getWordsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      15,
      f,
      proto.micro.service.language.entities.v1.Word.serializeBinaryToWriter
    );
  }
};


/**
 * optional gorm.types.UUID id = 1;
 * @return {?proto.gorm.types.UUID}
 */
proto.micro.service.language.entities.v1.Skill.prototype.getId = function() {
  return /** @type{?proto.gorm.types.UUID} */ (
    jspb.Message.getWrapperField(this, third_party_proto_protoc$gen$gorm_types_types_pb.UUID, 1));
};


/**
 * @param {?proto.gorm.types.UUID|undefined} value
 * @return {!proto.micro.service.language.entities.v1.Skill} returns this
*/
proto.micro.service.language.entities.v1.Skill.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.micro.service.language.entities.v1.Skill} returns this
 */
proto.micro.service.language.entities.v1.Skill.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.micro.service.language.entities.v1.Skill.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.Timestamp created_at = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.micro.service.language.entities.v1.Skill.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.micro.service.language.entities.v1.Skill} returns this
*/
proto.micro.service.language.entities.v1.Skill.prototype.setCreatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.micro.service.language.entities.v1.Skill} returns this
 */
proto.micro.service.language.entities.v1.Skill.prototype.clearCreatedAt = function() {
  return this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.micro.service.language.entities.v1.Skill.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.micro.service.language.entities.v1.Skill.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.micro.service.language.entities.v1.Skill} returns this
*/
proto.micro.service.language.entities.v1.Skill.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.micro.service.language.entities.v1.Skill} returns this
 */
proto.micro.service.language.entities.v1.Skill.prototype.clearUpdatedAt = function() {
  return this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.micro.service.language.entities.v1.Skill.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.Timestamp deleted_at = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.micro.service.language.entities.v1.Skill.prototype.getDeletedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.micro.service.language.entities.v1.Skill} returns this
*/
proto.micro.service.language.entities.v1.Skill.prototype.setDeletedAt = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.micro.service.language.entities.v1.Skill} returns this
 */
proto.micro.service.language.entities.v1.Skill.prototype.clearDeletedAt = function() {
  return this.setDeletedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.micro.service.language.entities.v1.Skill.prototype.hasDeletedAt = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.StringValue dependencies = 5;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.micro.service.language.entities.v1.Skill.prototype.getDependencies = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 5));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.micro.service.language.entities.v1.Skill} returns this
*/
proto.micro.service.language.entities.v1.Skill.prototype.setDependencies = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.micro.service.language.entities.v1.Skill} returns this
 */
proto.micro.service.language.entities.v1.Skill.prototype.clearDependencies = function() {
  return this.setDependencies(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.micro.service.language.entities.v1.Skill.prototype.hasDependencies = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional bool disabled = 6;
 * @return {boolean}
 */
proto.micro.service.language.entities.v1.Skill.prototype.getDisabled = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.micro.service.language.entities.v1.Skill} returns this
 */
proto.micro.service.language.entities.v1.Skill.prototype.setDisabled = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional int32 lesson_number = 7;
 * @return {number}
 */
proto.micro.service.language.entities.v1.Skill.prototype.getLessonNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.micro.service.language.entities.v1.Skill} returns this
 */
proto.micro.service.language.entities.v1.Skill.prototype.setLessonNumber = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional google.protobuf.StringValue description = 8;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.micro.service.language.entities.v1.Skill.prototype.getDescription = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 8));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.micro.service.language.entities.v1.Skill} returns this
*/
proto.micro.service.language.entities.v1.Skill.prototype.setDescription = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.micro.service.language.entities.v1.Skill} returns this
 */
proto.micro.service.language.entities.v1.Skill.prototype.clearDescription = function() {
  return this.setDescription(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.micro.service.language.entities.v1.Skill.prototype.hasDescription = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional bool locked = 9;
 * @return {boolean}
 */
proto.micro.service.language.entities.v1.Skill.prototype.getLocked = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.micro.service.language.entities.v1.Skill} returns this
 */
proto.micro.service.language.entities.v1.Skill.prototype.setLocked = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * optional google.protobuf.StringValue type = 10;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.micro.service.language.entities.v1.Skill.prototype.getType = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 10));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.micro.service.language.entities.v1.Skill} returns this
*/
proto.micro.service.language.entities.v1.Skill.prototype.setType = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.micro.service.language.entities.v1.Skill} returns this
 */
proto.micro.service.language.entities.v1.Skill.prototype.clearType = function() {
  return this.setType(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.micro.service.language.entities.v1.Skill.prototype.hasType = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional string title = 11;
 * @return {string}
 */
proto.micro.service.language.entities.v1.Skill.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.micro.service.language.entities.v1.Skill} returns this
 */
proto.micro.service.language.entities.v1.Skill.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string url_title = 12;
 * @return {string}
 */
proto.micro.service.language.entities.v1.Skill.prototype.getUrlTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.micro.service.language.entities.v1.Skill} returns this
 */
proto.micro.service.language.entities.v1.Skill.prototype.setUrlTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional google.protobuf.StringValue category = 13;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.micro.service.language.entities.v1.Skill.prototype.getCategory = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 13));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.micro.service.language.entities.v1.Skill} returns this
*/
proto.micro.service.language.entities.v1.Skill.prototype.setCategory = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.micro.service.language.entities.v1.Skill} returns this
 */
proto.micro.service.language.entities.v1.Skill.prototype.clearCategory = function() {
  return this.setCategory(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.micro.service.language.entities.v1.Skill.prototype.hasCategory = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional int32 index = 14;
 * @return {number}
 */
proto.micro.service.language.entities.v1.Skill.prototype.getIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.micro.service.language.entities.v1.Skill} returns this
 */
proto.micro.service.language.entities.v1.Skill.prototype.setIndex = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};


/**
 * repeated Word words = 15;
 * @return {!Array<!proto.micro.service.language.entities.v1.Word>}
 */
proto.micro.service.language.entities.v1.Skill.prototype.getWordsList = function() {
  return /** @type{!Array<!proto.micro.service.language.entities.v1.Word>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.micro.service.language.entities.v1.Word, 15));
};


/**
 * @param {!Array<!proto.micro.service.language.entities.v1.Word>} value
 * @return {!proto.micro.service.language.entities.v1.Skill} returns this
*/
proto.micro.service.language.entities.v1.Skill.prototype.setWordsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 15, value);
};


/**
 * @param {!proto.micro.service.language.entities.v1.Word=} opt_value
 * @param {number=} opt_index
 * @return {!proto.micro.service.language.entities.v1.Word}
 */
proto.micro.service.language.entities.v1.Skill.prototype.addWords = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 15, opt_value, proto.micro.service.language.entities.v1.Word, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.micro.service.language.entities.v1.Skill} returns this
 */
proto.micro.service.language.entities.v1.Skill.prototype.clearWordsList = function() {
  return this.setWordsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.micro.service.language.entities.v1.Word.prototype.toObject = function(opt_includeInstance) {
  return proto.micro.service.language.entities.v1.Word.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.micro.service.language.entities.v1.Word} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.micro.service.language.entities.v1.Word.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = msg.getId()) && third_party_proto_protoc$gen$gorm_types_types_pb.UUID.toObject(includeInstance, f),
    createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    deletedAt: (f = msg.getDeletedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    content: jspb.Message.getFieldWithDefault(msg, 5, ""),
    audioSrc: jspb.Message.getFieldWithDefault(msg, 6, ""),
    skill: (f = msg.getSkill()) && proto.micro.service.language.entities.v1.Skill.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.micro.service.language.entities.v1.Word}
 */
proto.micro.service.language.entities.v1.Word.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.micro.service.language.entities.v1.Word;
  return proto.micro.service.language.entities.v1.Word.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.micro.service.language.entities.v1.Word} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.micro.service.language.entities.v1.Word}
 */
proto.micro.service.language.entities.v1.Word.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new third_party_proto_protoc$gen$gorm_types_types_pb.UUID;
      reader.readMessage(value,third_party_proto_protoc$gen$gorm_types_types_pb.UUID.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDeletedAt(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setContent(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setAudioSrc(value);
      break;
    case 7:
      var value = new proto.micro.service.language.entities.v1.Skill;
      reader.readMessage(value,proto.micro.service.language.entities.v1.Skill.deserializeBinaryFromReader);
      msg.setSkill(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.micro.service.language.entities.v1.Word.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.micro.service.language.entities.v1.Word.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.micro.service.language.entities.v1.Word} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.micro.service.language.entities.v1.Word.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      third_party_proto_protoc$gen$gorm_types_types_pb.UUID.serializeBinaryToWriter
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDeletedAt();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getContent();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getAudioSrc();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getSkill();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.micro.service.language.entities.v1.Skill.serializeBinaryToWriter
    );
  }
};


/**
 * optional gorm.types.UUID id = 1;
 * @return {?proto.gorm.types.UUID}
 */
proto.micro.service.language.entities.v1.Word.prototype.getId = function() {
  return /** @type{?proto.gorm.types.UUID} */ (
    jspb.Message.getWrapperField(this, third_party_proto_protoc$gen$gorm_types_types_pb.UUID, 1));
};


/**
 * @param {?proto.gorm.types.UUID|undefined} value
 * @return {!proto.micro.service.language.entities.v1.Word} returns this
*/
proto.micro.service.language.entities.v1.Word.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.micro.service.language.entities.v1.Word} returns this
 */
proto.micro.service.language.entities.v1.Word.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.micro.service.language.entities.v1.Word.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.Timestamp created_at = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.micro.service.language.entities.v1.Word.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.micro.service.language.entities.v1.Word} returns this
*/
proto.micro.service.language.entities.v1.Word.prototype.setCreatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.micro.service.language.entities.v1.Word} returns this
 */
proto.micro.service.language.entities.v1.Word.prototype.clearCreatedAt = function() {
  return this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.micro.service.language.entities.v1.Word.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.micro.service.language.entities.v1.Word.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.micro.service.language.entities.v1.Word} returns this
*/
proto.micro.service.language.entities.v1.Word.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.micro.service.language.entities.v1.Word} returns this
 */
proto.micro.service.language.entities.v1.Word.prototype.clearUpdatedAt = function() {
  return this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.micro.service.language.entities.v1.Word.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.Timestamp deleted_at = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.micro.service.language.entities.v1.Word.prototype.getDeletedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.micro.service.language.entities.v1.Word} returns this
*/
proto.micro.service.language.entities.v1.Word.prototype.setDeletedAt = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.micro.service.language.entities.v1.Word} returns this
 */
proto.micro.service.language.entities.v1.Word.prototype.clearDeletedAt = function() {
  return this.setDeletedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.micro.service.language.entities.v1.Word.prototype.hasDeletedAt = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string content = 5;
 * @return {string}
 */
proto.micro.service.language.entities.v1.Word.prototype.getContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.micro.service.language.entities.v1.Word} returns this
 */
proto.micro.service.language.entities.v1.Word.prototype.setContent = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string audio_src = 6;
 * @return {string}
 */
proto.micro.service.language.entities.v1.Word.prototype.getAudioSrc = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.micro.service.language.entities.v1.Word} returns this
 */
proto.micro.service.language.entities.v1.Word.prototype.setAudioSrc = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional Skill Skill = 7;
 * @return {?proto.micro.service.language.entities.v1.Skill}
 */
proto.micro.service.language.entities.v1.Word.prototype.getSkill = function() {
  return /** @type{?proto.micro.service.language.entities.v1.Skill} */ (
    jspb.Message.getWrapperField(this, proto.micro.service.language.entities.v1.Skill, 7));
};


/**
 * @param {?proto.micro.service.language.entities.v1.Skill|undefined} value
 * @return {!proto.micro.service.language.entities.v1.Word} returns this
*/
proto.micro.service.language.entities.v1.Word.prototype.setSkill = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.micro.service.language.entities.v1.Word} returns this
 */
proto.micro.service.language.entities.v1.Word.prototype.clearSkill = function() {
  return this.setSkill(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.micro.service.language.entities.v1.Word.prototype.hasSkill = function() {
  return jspb.Message.getField(this, 7) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.micro.service.language.entities.v1.Language.repeatedFields_ = [9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.micro.service.language.entities.v1.Language.prototype.toObject = function(opt_includeInstance) {
  return proto.micro.service.language.entities.v1.Language.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.micro.service.language.entities.v1.Language} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.micro.service.language.entities.v1.Language.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = msg.getId()) && third_party_proto_protoc$gen$gorm_types_types_pb.UUID.toObject(includeInstance, f),
    createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    deletedAt: (f = msg.getDeletedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    name: jspb.Message.getFieldWithDefault(msg, 5, ""),
    abbreviation: jspb.Message.getFieldWithDefault(msg, 6, ""),
    flagSrc: jspb.Message.getFieldWithDefault(msg, 7, ""),
    skillsList: jspb.Message.toObjectList(msg.getSkillsList(),
    proto.micro.service.language.entities.v1.Skill.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.micro.service.language.entities.v1.Language}
 */
proto.micro.service.language.entities.v1.Language.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.micro.service.language.entities.v1.Language;
  return proto.micro.service.language.entities.v1.Language.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.micro.service.language.entities.v1.Language} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.micro.service.language.entities.v1.Language}
 */
proto.micro.service.language.entities.v1.Language.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new third_party_proto_protoc$gen$gorm_types_types_pb.UUID;
      reader.readMessage(value,third_party_proto_protoc$gen$gorm_types_types_pb.UUID.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDeletedAt(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setAbbreviation(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setFlagSrc(value);
      break;
    case 9:
      var value = new proto.micro.service.language.entities.v1.Skill;
      reader.readMessage(value,proto.micro.service.language.entities.v1.Skill.deserializeBinaryFromReader);
      msg.addSkills(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.micro.service.language.entities.v1.Language.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.micro.service.language.entities.v1.Language.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.micro.service.language.entities.v1.Language} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.micro.service.language.entities.v1.Language.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      third_party_proto_protoc$gen$gorm_types_types_pb.UUID.serializeBinaryToWriter
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDeletedAt();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getAbbreviation();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getFlagSrc();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getSkillsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      proto.micro.service.language.entities.v1.Skill.serializeBinaryToWriter
    );
  }
};


/**
 * optional gorm.types.UUID id = 1;
 * @return {?proto.gorm.types.UUID}
 */
proto.micro.service.language.entities.v1.Language.prototype.getId = function() {
  return /** @type{?proto.gorm.types.UUID} */ (
    jspb.Message.getWrapperField(this, third_party_proto_protoc$gen$gorm_types_types_pb.UUID, 1));
};


/**
 * @param {?proto.gorm.types.UUID|undefined} value
 * @return {!proto.micro.service.language.entities.v1.Language} returns this
*/
proto.micro.service.language.entities.v1.Language.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.micro.service.language.entities.v1.Language} returns this
 */
proto.micro.service.language.entities.v1.Language.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.micro.service.language.entities.v1.Language.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.Timestamp created_at = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.micro.service.language.entities.v1.Language.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.micro.service.language.entities.v1.Language} returns this
*/
proto.micro.service.language.entities.v1.Language.prototype.setCreatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.micro.service.language.entities.v1.Language} returns this
 */
proto.micro.service.language.entities.v1.Language.prototype.clearCreatedAt = function() {
  return this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.micro.service.language.entities.v1.Language.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.micro.service.language.entities.v1.Language.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.micro.service.language.entities.v1.Language} returns this
*/
proto.micro.service.language.entities.v1.Language.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.micro.service.language.entities.v1.Language} returns this
 */
proto.micro.service.language.entities.v1.Language.prototype.clearUpdatedAt = function() {
  return this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.micro.service.language.entities.v1.Language.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.Timestamp deleted_at = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.micro.service.language.entities.v1.Language.prototype.getDeletedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.micro.service.language.entities.v1.Language} returns this
*/
proto.micro.service.language.entities.v1.Language.prototype.setDeletedAt = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.micro.service.language.entities.v1.Language} returns this
 */
proto.micro.service.language.entities.v1.Language.prototype.clearDeletedAt = function() {
  return this.setDeletedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.micro.service.language.entities.v1.Language.prototype.hasDeletedAt = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string name = 5;
 * @return {string}
 */
proto.micro.service.language.entities.v1.Language.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.micro.service.language.entities.v1.Language} returns this
 */
proto.micro.service.language.entities.v1.Language.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string abbreviation = 6;
 * @return {string}
 */
proto.micro.service.language.entities.v1.Language.prototype.getAbbreviation = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.micro.service.language.entities.v1.Language} returns this
 */
proto.micro.service.language.entities.v1.Language.prototype.setAbbreviation = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string flag_src = 7;
 * @return {string}
 */
proto.micro.service.language.entities.v1.Language.prototype.getFlagSrc = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.micro.service.language.entities.v1.Language} returns this
 */
proto.micro.service.language.entities.v1.Language.prototype.setFlagSrc = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * repeated Skill skills = 9;
 * @return {!Array<!proto.micro.service.language.entities.v1.Skill>}
 */
proto.micro.service.language.entities.v1.Language.prototype.getSkillsList = function() {
  return /** @type{!Array<!proto.micro.service.language.entities.v1.Skill>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.micro.service.language.entities.v1.Skill, 9));
};


/**
 * @param {!Array<!proto.micro.service.language.entities.v1.Skill>} value
 * @return {!proto.micro.service.language.entities.v1.Language} returns this
*/
proto.micro.service.language.entities.v1.Language.prototype.setSkillsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 9, value);
};


/**
 * @param {!proto.micro.service.language.entities.v1.Skill=} opt_value
 * @param {number=} opt_index
 * @return {!proto.micro.service.language.entities.v1.Skill}
 */
proto.micro.service.language.entities.v1.Language.prototype.addSkills = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, proto.micro.service.language.entities.v1.Skill, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.micro.service.language.entities.v1.Language} returns this
 */
proto.micro.service.language.entities.v1.Language.prototype.clearSkillsList = function() {
  return this.setSkillsList([]);
};


goog.object.extend(exports, proto.micro.service.language.entities.v1);
